# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: line.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nline.proto\x12\x08\x64\x61r.lldc\"\xa3\x01\n\tDataEntry\x12!\n\x07strokes\x18\x01 \x03(\x0b\x32\x10.dar.lldc.Stroke\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x0e\n\x06userID\x18\x03 \x01(\t\x12\x10\n\x08\x64\x65viceID\x18\x04 \x01(\t\x12\r\n\x05label\x18\x05 \x01(\t\x12\n\n\x02id\x18\x06 \x01(\t\x12&\n\tlabelType\x18\x07 \x01(\x0e\x32\x13.dar.lldc.LabelType\"<\n\nPointDelta\x12\x0e\n\x06\x64\x65ltaX\x18\x01 \x01(\x02\x12\x0e\n\x06\x64\x65ltaY\x18\x02 \x01(\x02\x12\x0e\n\x06\x64\x65ltaT\x18\x03 \x01(\r\"u\n\x06Stroke\x12\x1b\n\x13\x66irstPointTimeStamp\x18\x01 \x01(\x04\x12\x13\n\x0b\x66irstPointX\x18\x02 \x01(\x02\x12\x13\n\x0b\x66irstPointY\x18\x03 \x01(\x02\x12$\n\x06points\x18\x04 \x03(\x0b\x32\x14.dar.lldc.PointDelta*\x16\n\tLabelType\x12\t\n\x05LATEX\x10\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'line_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LABELTYPE._serialized_start=371
  _LABELTYPE._serialized_end=393
  _DATAENTRY._serialized_start=25
  _DATAENTRY._serialized_end=188
  _POINTDELTA._serialized_start=190
  _POINTDELTA._serialized_end=250
  _STROKE._serialized_start=252
  _STROKE._serialized_end=369
# @@protoc_insertion_point(module_scope)
